// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailOtp struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Otp       string             `json:"otp"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	UserName     pgtype.Text        `json:"user_name"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	Role         pgtype.Text        `json:"role"`
	Source       pgtype.Text        `json:"source"`
	CountryCode  pgtype.Text        `json:"country_code"`
	IsVerified   pgtype.Bool        `json:"is_verified"`
	IsActive     pgtype.Bool        `json:"is_active"`
	Image        pgtype.Text        `json:"image"`
	Gender       pgtype.Text        `json:"gender"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	IsBan        pgtype.Bool        `json:"is_ban"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
