// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailOtp struct {
	ID        pgtype.UUID        `json:"id"`
	Email     string             `json:"email"`
	Otp       string             `json:"otp"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	UserName     *string            `json:"user_name"`
	Email        string             `json:"email"`
	PasswordHash *string            `json:"password_hash"`
	Role         *string            `json:"role"`
	Source       *string            `json:"source"`
	CountryCode  *string            `json:"country_code"`
	IsVerified   *bool              `json:"is_verified"`
	IsActive     *bool              `json:"is_active"`
	Image        *string            `json:"image"`
	Gender       *string            `json:"gender"`
	RefreshToken *string            `json:"refresh_token"`
	IsBan        *bool              `json:"is_ban"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
