// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	FindExistingUserByEmail(ctx context.Context, email string) (*bool, error)
	InsertEmailOtp(ctx context.Context, arg InsertEmailOtpParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
}

var _ Querier = (*Queries)(nil)
