// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findExistingUserByEmail = `-- name: FindExistingUserByEmail :one
select is_verified from users where email = $1
`

func (q *Queries) FindExistingUserByEmail(ctx context.Context, email string) (*bool, error) {
	row := q.db.QueryRow(ctx, findExistingUserByEmail, email)
	var is_verified *bool
	err := row.Scan(&is_verified)
	return is_verified, err
}

const insertEmailOtp = `-- name: InsertEmailOtp :exec
INSERT INTO email_otps (email, otp, expires_at) VALUES ($1, $2, $3)
`

type InsertEmailOtpParams struct {
	Email     string             `json:"email"`
	Otp       string             `json:"otp"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) InsertEmailOtp(ctx context.Context, arg InsertEmailOtpParams) error {
	_, err := q.db.Exec(ctx, insertEmailOtp, arg.Email, arg.Otp, arg.ExpiresAt)
	return err
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (
    user_name, 
    email, 
    password_hash, 
    role, 
    source, 
    country_code, 
    gender
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
`

type InsertUserParams struct {
	UserName     *string `json:"user_name"`
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
	Role         *string `json:"role"`
	Source       *string `json:"source"`
	CountryCode  *string `json:"country_code"`
	Gender       *string `json:"gender"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.UserName,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.Source,
		arg.CountryCode,
		arg.Gender,
	)
	return err
}
